blipRenderDistance = 150.0
interactDistance = 1.5

Clothing_locations = {
------ POLICE STATIONS --------
  {--vinewood
  coords = vec(607.94, 17.06, 81.74),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
}, 
{ -- MRPD
 coords = vec(452.05, -991.05, 29.7),
 MarkerId = 1,
 MarkerSize = vec(1.0, 1.0, 1.5),
 Color = vec(0.0, 0.0, 255.0),
},
{ -- davis
  coords = vec(356.4, -1609.71, 28.29),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- vespucci 
  coords = vec(-1081.73, -829.0, 14.64),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- pleto bay
  coords = vec(-438.81, 6007.81, 36),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- sandy
  coords = vec(1848.23, 3687.86, 33.27),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ --  La marsa
  coords = vec(852.99, -1306.75, 27.34),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ --  Custody Room
  coords = vec(-211.97, -1262.87, 30.29),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
---------- ARMY DLCS --------
{-- army base
    coords = vec(-2350.04, 3267.59, 31.81),
    MarkerId = 1,
    MarkerSize = vec(1.0, 1.0, 1.5),
    Color = vec(0.0, 0.0, 255.0), 
},
----------- LFB FIRE STATIONS ---------
{ -- DAVIS FIRE 
  coords = vec(214.08, -1658.19, 28.8),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- EL RACHO
  coords = vec(1211.58, -1474.00, 33.86),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- PELTO FIRE
coords = vec(-379.16, 6118.08, 30.85),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- SANDY FIRE
coords = vec(1674.35, 3596.38, 35.48),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},

-------- NHS STATIONS ---------------
{ -- PILLBOX HOSP
  coords = vec(298.61, -599.29, 42.28),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- DAVIS HOSP
coords = vec(313.44, -1409.91, 31.51),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- MORNIGWOOD AMB STATION
coords = vec(-1431.11, -254.15, 45.48),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- MOUNT ZONAH
coords = vec(-437.78, -308.08, 33.91),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- PIER Station
coords = vec(-1587.35, -845.7, 9.13),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- SANDY
  coords = vec(1842.61, 3678.13, 33.27),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
-------- HIGHWAYS STATIONS -----------
{ --MAIN HIGHWAYS
coords = vec(-184.26, -1162.98, 22.67),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
},
{ -- LOS SANTOS FREEWAY
  coords = vec(1537.62, 812.09, 76.66),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
}, 
{ -- HQ
  coords = vec(-692.09, -409.34, 33.98),
        MarkerId = 1,
        MarkerSize = vec(1.0, 1.0, 1.5),
        Color = vec(0.0, 0.0, 255.0),
}, 
----------- MODERATOR AREAS -----------
{ -- SANDY Feul Station
  coords = vec(1996.5, 3779.99, 31.18),
  MarkerId = 1,
  MarkerSize = vec(1.0, 1.0, 1.5),
  Color = vec(0.0, 0.0, 255.0),
},
{ -- PELTO CHRUCH
coords = vec(-292.59, 6137.06, 30.48),
MarkerId = 1,
MarkerSize = vec(1.0, 1.0, 1.5),
Color = vec(0.0, 0.0, 255.0),
},
{-- BENYYS
coords = vec(-17.72, -1055.31, 31.4),
MarkerId = 1,
MarkerSize = vec(1.0, 1.0, 1.5),
Color = vec(0.0, 0.0, 255.0),
},
--{ -- BEAN MCHINE
--coords = vec(126.77, -1033.71, 29.28),
--MarkerId = 43,
--MarkerSize = vec(0.5, 0.5, 0.5),
--Color = vec(0.0, 0.0, 255.0)
--},
{ --- MULTI STORY DINNER
coords = vec(481.26, -912.99, 34.97),
MarkerId = 1,
MarkerSize = vec(1.0, 1.0, 1.5),
Color = vec(0.0, 0.0, 255.0),
},

}

Clothing_Catagories = {
  {
    ace = 'PCSO',
    name = 'Police Community Support Officer',
    clothes = {
      ['PCSO 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 7,
        mom = 33,
        dad = 2,
        hair_1 = 38,
      hair_color_1 = 4,
        mask_1 = 11,
        arms = 0,
        pants_1 = 5,
        bags_1 = 48,
        shoes_1 = 25,
        neckarm_1 =108,
        tshirt_1 = 8,
        bproof_1 = 29,
        decals_1 = 6,
        torso_1 = 1,
        torso_2 = 9
      },
      ['PCSO 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 7,
        mom = 6,
        dad = 1,
        hair_1 = 38,
      hair_color_1 = 59,
        mask_1 = 11,
        arms = 0,
        pants_1 = 5,
        bags_1 = 48,
        shoes_1 = 25,
        neckarm_1 =108,
        tshirt_1 = 8,
        bproof_1 = 8,
        decals_1 = 6,
        torso_1 = 1,
        torso_2 = 9
      },
      ['PCSO 3'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 8,
        mom = 11,
        dad = 2,
        hair_1 = 1,
      hair_color_1 = 6,
        mask_1 = 11,
        arms = 0,
        pants_1 = 5,
        bags_1 = 48,
        shoes_1 = 25,
        neckarm_1 =108,
        tshirt_1 = 8,
        bproof_1 = 7,
        decals_1 = 6,
        torso_1 = 1,
        torso_2 = 9
      },
      ['PCSO Bike Uniform'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 0,
        mom = 7,
        dad = 32,
        hair_1 = 1,
      hair_color_1 = 10,
        mask_1 = 11,
        arms = 11,
        pants_1 = 12,
        bags_1 = 48,
        shoes_1 = 9,
        neckarm_1 = 0,
        tshirt_1 = 8,
        bproof_1 = 0,
        decals_1 = 5,
        torso_1 = 9,
        torso_2 = 1
      }
    }
  },  
  {
    ace = 'MPSRPU',
    name = 'Roads Policing Unit',
    clothes = {
      ['RPU 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 6,
        mask_1 = 11,
      hair_1 = 12,
      hair_color_1 = 3,
        arms = 4,
        pants_1 = 5,
        bags_1 = 30,
        shoes_1 = 25,
        neckarm_1 = 6,
        tshirt_1 = 11,
        bproof_1 = 6,
        decals_1 = 3,
        torso_1 = 5,
      },
      ['Biker RPU 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 25,
        mask_1 = 11,
      dad = 13,
      mom = 8,
        arms = 0,
        pants_1 = 47,
        bags_1 = 20,
        shoes_1 = 25,
        neckarm_1 = 4,
        tshirt_1 = 10,
        bproof_1 = 0,
        decals_1 = 2,
        torso_1 = 24,
      },
      ['RPU 3'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 6,
        mask_1 = 11,
      hair_1 = 22,
      hair_color_1 = 1,
      dad = 3,
      mom = 30,
        arms = 0,
        pants_1 = 5,
        bags_1 = 9,
        shoes_1 = 25,
        tshirt_1 = 9,
        bproof_1 = 8,
        decals_1 = 7,
        torso_1 = 1,
      }
    }  
  },       
    
  {
    ace = 'CIU',
    name = 'Collision Investigation Unit',
    clothes = {
      ['RPU outfit 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 15,
        pants_1 = 0,
        bags_1 = 0,
        shoes_1 = 0,
        neckarm_1 = 0,
        tshirt_1 = 0,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 0,
      },
      ['RPU outfit 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 15,
        pants_1 = 0,
        bags_1 = 0,
        shoes_1 = 0,
        neckarm_1 = 0,
        tshirt_1 = 0,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 0,
      }
    }
  },

  {
    ace = 'MPSTFU',
    name = 'TFU',
    clothes = {
      ['Tatical TFU with mask'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 19,
        mask_1 = 53,
        arms = 8,
      lefthand_1 = 2,
        pants_1 = 5,
        bags_1 = 2,
        shoes_1 = 25,
        neckarm_1 = 2,
        tshirt_1 = 8,
        bproof_1 = 9,
        decals_1 = 25,
        torso_1 = 3
      },
      ['Tatical TFU without mask'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 19,
        mask_1 = 11,
        mom = 36,
        dad = 6,
        hair_1 = 1,
        hair_color_1 = 60,
        arms = 11,
        pants_1 = 5,
        bags_1 = 2,
        shoes_1 = 25,
        neckarm_1 = 2,
        tshirt_1 = 8,
        bproof_1 = 9,
        decals_1 = 25,
        torso_1 = 3,
      },
      ['TFU 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 19,
        mask_1 = 52,
        arms = 11,
        pants_1 = 5,
        bags_1 = 20,
        shoes_1 = 25,
        neckarm_1 = 2,
        tshirt_1 = 8,
        bproof_1 = 12,
        decals_1 = 5,
        torso_1 = 3
      },
      ['TFU 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
      mom = 33,
      dad = 21,
      hair_1 = 3,
        glasses_1 = 15,
      hair_color_1 = 12,
      glasses_2 = 8,
        mask_1 = 11,
        arms = 4,
        pants_1 = 5,
        bags_1 = 2,
        shoes_1 = 12,
        neckarm_1 = 2,
        tshirt_1 = 8,
        bproof_1 = 9,
        decals_1 = 0,
        torso_1 = 5
      },
      ['TFU 3'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
      mom = 38,
      dad = 3,
      hair_1 = 47,
        glasses_1 = 15,
      hair_color_1 = 1,
        mask_1 = -1,
        arms = 11,
        pants_1 = 5,
        bags_1 = 20,
        shoes_1 = 25,
        neckarm_1 = 8,
        tshirt_1 = 6,
        bproof_1 = 0,
        decals_1 = 2,
        torso_1 = 2
      }
    }
  },

  {
    ace = 'MPSCTSFO',
    name = 'CTSFO',
    clothes = {
      ['CTSFO 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 18,
        mom = 41,
        dad = 34,
        mask_1 = 185,
        hair_1 = 0,
      hair_color_1 = 1,
        arms = 0,
        pants_1 = 11,
        pants_2 = 1,
        bags_1 = 4,
        shoes_1 = 25,
        neckarm_1 = 123,
        tshirt_1 = 73,
        bproof_1 = 36,
        decals_1 = 12,
        torso_1 = 141,
      },
      ['CTSFO 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 18,
        mom = 1,
        dad = 32,
        hair_1 = 1,
      hair_color_1 = 58,
        mask_1 = 185,
        arms = 1,
        pants_1 = 11,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 123,
        tshirt_1 = 69,
        bproof_1 = 35,
        decals_1 = 24,
        torso_1 = 138
      },
      ['CTSFO 3'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 19,
        mom = 1,
        dad = 32,
        hair_1 = 1,
      hair_color_1 = 58,
        mask_1 = -1,
        arms = 1,
        pants_1 = 123,
        bags_1 = 9,
        shoes_1 = 25,
        neckarm_1 = 8,
        tshirt_1 = 6,
        bproof_1 = 19,
        decals_1 = 61,
        torso_1 = 2
      }
    }
  },
  {
    ace = 'MPSDSU',
    name = 'Dog Support Unit',
    clothes = {
      ['DSU 1'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
        mom = 1,
        dad = 32,
        hair_1 = 1,
      hair_color_1 = 58,
        mask_1 = 11,
        arms = 4,
        pants_1 = 5,
        bags_1 = 21,
        shoes_1 = 25,
        neckarm_1 = 16,
        tshirt_1 = 8,
        bproof_1 = 14,
        decals_1 = 8,
        torso_1 = 5
      },
      ['DSU 2'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
        mom = 12,
        dad = 11,
        hair_1 = 2,
      hair_color_1 = 58,
        mask_1 = 11,
        arms = 4,
        pants_1 = 5,
        bags_1 = 9,
        shoes_1 = 12,
        neckarm_1 = 10,
        tshirt_1 = 9,
        bproof_1 = 14,
        decals_1 = 6,
        torso_1 = 5,
        torso_2 = 0
      },
      ['DSU 3'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
        mom = 16,
        dad = 19,
        hair_1 = 1,
      hair_color_1 = 58,
        mask_1 = 11,
        arms = 0,
        pants_1 = 5,
        bags_1 = 9,
        shoes_1 = 25,
        neckarm_1 = 16,
        tshirt_1 = 9,
        bproof_1 = 14,
        decals_1 = 9,
        torso_1 = 4
      }
    }
  },


  {
    ace = 'ADSU',
    name = 'Armed Dog Support Unit',
    clothes = {
      ['Armed Dog Vest'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = 1,
        mom = 9,
        dad = 30,
        hair_1 = 7,
      hair_color_1 = 55,
        mask_1 = 11,
        arms = 5,
        pants_1 = 5,
        bags_1 = 21,
        shoes_1 = 25,
        neckarm_1 = 8,
        tshirt_1 = 8,
        bproof_1 = 14,
        decals_1 = 6,
        torso_1 = 5
      }
    }
  },
    {
      ace = 'TOTAL',
      name = 'JKL Security',
      clothes = {
        ['Security 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 9,
          dad = 30,
          hair_1 = 7,
        hair_color_1 = 55,
          mask_1 = 11,
          arms = 6,
          pants_1 = 5,
          bags_1 = 0,
          shoes_1 = 25,
          neckarm_1 = 74,
          tshirt_1 = 77,
          bproof_1 = 37,
          decals_1 = 25,
          torso_1 = 142
        },
        ['Security 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 39,
          dad = 20,
          hair_1 = 4,
        hair_color_1 = 55,
          mask_1 = 11,
          arms = 6,
          pants_1 = 5,
          bags_1 = 5,
          shoes_1 = 25,
          neckarm_1 = 74,
          tshirt_1 = 77,
          bproof_1 = 38,
          bproof_2 = 1,
          decals_1 = 25,
          torso_1 = 142
        },
        ['Security 3'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 19,
          dad = 10,
          hair_1 = 8,
        hair_color_1 = 20,
          mask_1 = 11,
          arms = 6,
          pants_1 = 5,
          bags_1 = 6,
          shoes_1 = 25,
          neckarm_1 = 74,
          tshirt_1 = 77,
          bproof_1 = 39,
          decals_1 = 25,
          torso_1 = 142
        },
        ['Security 4'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 26,
          dad = 19,
          hair_1 = 2,
        hair_color_1 = 2,
          mask_1 = 11,
          arms = 6,
          pants_1 = 5,
          bags_1 = 7,
          shoes_1 = 25,
          neckarm_1 = 74,
          tshirt_1 = 77,
          bproof_1 = 39,
          decals_1 = 25,
          torso_1 = 142
        }
      }
    },
    {
      ace = 'MPSCID',
      name = 'Custody Room',
      clothes = {
        ['Custody Officer'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          beard_1 = 4,
          beard_2 = 100,
          beard_3 = 1,
          beard_4 = 0,
          hair_1 = 2,
        hair_color_1 = 1,
          mask_1 = 0,
          arms = 99,
          arms_2 = 9,
          pants_1 = 143,
          bags_1 = 0,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 0,
          tshirt_1 = 16,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 1,
          torso_2 = 10
        }
      }
    },

    {
      ace = 'MPSCID',
      name = 'Criminal Investigations Unit',
      clothes = {
        ['CID Suit'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 23,
          dad = 42,
          hair_1 = 13,
        hair_color_1 = 5,
          mask_1 = 121,
          arms = 11,
          pants_1 = 96,
          bags_1 = 48,
          shoes_1 = 20,
          neckarm_1 = 0,
          neckarm_2 = 0,
          tshirt_1 = 15,
          tshirt_2 = 0,
          decals_1 = 0,
        torso_1 = 43
        },
        ['CID Body Armor'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 1,  
        beard_1 = 3,      
          mom = 22,
          dad = 12,
          hair_1 = 4,
        hair_color_1 = 1,
          mask_1 = 121,
          arms = 0,
          pants_1 = 48,
          pants_2 = 3,
          bags_1 = 0,
          shoes_1 = 15,
          neckarm_1 = 0,
          tshirt_1 = 11,
          bproof_1 = 15,
          decals_1 = 6,
          torso_1 = 31
        },
        ['Leather Jacket'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          hair_1 = 5,
        hair_color_1 = 3,
          mask_1 = 11,
          arms = 1,
          pants_1 = 24,
          bags_1 = 30,
          shoes_1 = 12,
          neckarm_1 = 0,
          tshirt_1 = 75,
          bproof_1 = 0,
          decals_1 = 60,
          torso_1 = 64
        },
        ['Custody Officer'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          beard_1 = 4,
          beard_2 = 100,
          beard_3 = 1,
          beard_4 = 0,
          hair_1 = 2,
        hair_color_1 = 1,
          mask_1 = 0,
          arms = 99,
          arms_2 = 9,
          pants_1 = 143,
          bags_1 = 0,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 5,
          torso_1 = 1
        },
        ['Undercover Harness'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 32,
          dad = 22,
          hair_1 = 2,
        hair_color_1 = 6,
          mask_1 = 11,
          arms = 6,
          pants_1 = 47,
          bags_1 = 0,
          shoes_1 = 1,
          neckarm_1 = 14,
          tshirt_1 = 15,
          bproof_1 = 32,
          decals_1 = 23,
          torso_1 = 89
        }
      }
    },
    {
      ace = 'MPSNCA',
      name = 'National Crimes Agency',
      clothes = {
        ['NCA 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 1,
          mask_1 = 120,
          mom = 12,
          dad = 22,
          hair_1 = 11,
        hair_color_1 = 3,
          arms = 4,
          pants_1 = 5,
          bags_1 = 21,
          shoes_1 = 25,
          neckarm_1 = 2,
          tshirt_1 = 10,
          bproof_1 = 13,
          decals_1 = 6,
          torso_1 = 5
        },
        ['NCA 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 11,
          mom = 12,
          dad = 22,
          hair_1 = 11,
        hair_color_1 = 2,
          arms = 1,
          pants_1 = 129,
          bags_1 = 0,
          shoes_1 = 21,
          neckarm_1 = 1,
          tshirt_1 = 11,
          bproof_1 = 13,
          decals_1 = 3,
          torso_1 = 31
        }
      }
    },
      {
        ace = 'CSI',
        name = 'Crime Scene investigation',
        clothes = {
          ['CSI 1'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = 1,
            mask_1 = 11,
            beard_1 = 8,
            beard_2 = 100,
            beard_3 = 4,
            beard_4 = 0,
            mom = 11,
            dad = 21,
            hair_1 = 4,
          hair_color_1 = 4,
            arms = 11,
            pants_1 = 5,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 5,
            tshirt_1 = 8,
            bproof_1 = 0,
            decals_1 = 5,
            torso_1 = 14,
            torso_2 = 1
  
          },
          ['CSI 2'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 11,
            mom = 12,
            dad = 22,
            beard_1 = 19,
            beard_2 = 100,
            beard_3 = 5,
            beard_4 = 0,
            hair_1 = 13,
          hair_color_1 = 8,
            arms = 6,
            pants_1 = 5,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 4,
            tshirt_1 = 8,
            bproof_1 = 0,
            decals_1 = 2,
            torso_1 = 130
          }
        }
      },
    {
      ace = 'LASHEMS',
      name = 'HEMS',
      clothes = {
        ['NPAS Piot Viser Up'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 22,
          mom = 22,
          dad = 23,
          hair_1 = 4,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 22,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 25,
          torso_2 = 2,
        },
      }
    },       
    {
      ace = 'MPSNPAS',
      name = 'National Police Air Service',
      clothes = {
        ['NPAS Piot Viser Up'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 22,
          mom = 22,
          dad = 23,
          hair_1 = 4,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 22,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 25,
          torso_2 = 2,
        },
        ['NPAS Piot Viser Down'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 23,
          mask_1 = 0,
          mom = 14,
          dad = 24,
          hair_1 = 11,
        hair_color_1 = 5,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 22,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 25,
          torso_2 = 2,
        },
        ['NPAS Operator Viser Up'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 22,
          mask_1 = 0,
          mom = 2,
          dad = 21,
          hair_1 = 12,
        hair_color_1 = 3,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 22,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 25,
          torso_2 = 3,
        },
        ['NPAS Operator Viser Down'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 23,
          mom = 33,
          dad = 11,
          hair_1 = 4,
        hair_color_1 = 56,
          mask_1 = 0,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 22,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 25,
          torso_2 = 3,
        },
        ['NPAS Lounge Wear'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          mom = 44,
          dad = 2,
          hair_1 = 4,
        hair_color_1 = 1,
          arms = 1,
          pants_1 = 8,
          pants_2 = 1,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 177,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 26,
          torso_2 = 1,
        }
      }
    },
    {
      ace = 'METSGT',
      name = 'Police Sergeant',
      clothes = {
        ['Police HighVis Sergeant'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 7,
        mom = 21,
        dad = 22,
        hair_1 = 2,
        hair_color_1 = 58,
          mask_1 = 121,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 14,
          tshirt_1 = 9,
          bproof_1 = 2,
          bproof_2 = 1,
          decals_1 = 10,
          torso_1 = 1,
          torso_2 = 2
        },
        ['Police Black Vest Sergeant'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 7,
        mom = 21,
        dad = 22,
        hair_1 = 2,
        hair_color_1 = 58,
          mask_1 = 121,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 14,
          tshirt_1 = 9,
          bproof_1 = 30,
          decals_1 = 10,
          torso_1 = 1,
          torso_2 = 2
        },
        ['Police Sergeant Formals'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 7,
          mom = 9,
          dad = 1,
          hair_1 = 2,
        hair_color_1 = 1,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 35,
          torso_2 = 1,
        },
        ['Police Sergeant White shirt'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 7,
          mom = 9,
          dad = 1,
          hair_1 = 2,
        hair_color_1 = 1,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 10,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 30,
          decals_1 = 6,
          torso_1 = 31,
          torso_2 = 1,
        },
      }
    },
    {
      ace = 'BRONZE',
      name = 'Police inspector',
      clothes = {
        ['Police Black vest Inspector'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
        mom = 24,
        dad = 11,
        hair_1 = 1,
        hair_color_1 = 58,
          mask_1 = 11,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 14,
          tshirt_1 = 13,
          bproof_1 = 6,
          decals_1 = 10,
          torso_1 = 1,
          torso_2 = 3
        },
        ['TFU Inspector'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 1,
        mom = 24,
        dad = 11,
        hair_1 = 4,
       glasses_1 = 4,
        hair_color_1 = 4,
          mask_1 = 11,
          arms = 11,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 24,
          neckarm_1 = 8,
          tshirt_1 = 12,
          bproof_1 = 12,
          decals_1 = 0,
          torso_1 = 1,
          torso_2 = 3
        },
        ['Police HighVis Inspector'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
        mom = 31,
        dad = 12,
        hair_1 = 1,
        hair_color_1 = 58,
          mask_1 = 11,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 13,
          tshirt_1 = 13,
          bproof_1 = 2,
          bproof_2 = 2,
          decals_1 = 17,
          torso_1 = 1,
          torso_2 = 3
        },
        ['Police Inspector Formals'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
          mom = 22,
          dad = 30,
          hair_1 = 1,
        hair_color_1 = 3,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 19,
          torso_1 = 35,
          torso_2 = 2,
        },
        ['Police Inspector White shirt'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 26,
          dad = 10,
          hair_1 = 5,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 10,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 31,
          torso_2 = 2,
        },
        ['Chief Inspector Formals'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
          mom = 12,
          dad = 22,
          hair_1 = 1,
        hair_color_1 = 17,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 35,
          torso_2 = 3
        },
       ['Police Chief Inspector White shirt'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 26,
          dad = 10,
          hair_1 = 5,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 1,
          pants_1 = 27,
          bags_1 = 0,
          shoes_1 = 10,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 31,
          torso_2 = 3,
        },
        ['Police TFO Chief Inspector'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
        mom = 35,
        dad = 27,
        hair_1 = 2,
        hair_color_1 = 58,
          mask_1 = 121,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 2,
          tshirt_1 = 12,
          bproof_1 = 6,
          decals_1 = 1,
          torso_1 = 1,
          torso_2 = 3
        },
        ['Police HighVis Chief Inspector'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 8,
        mom = 22,
        dad = 21,
        hair_1 = 1,
        hair_color_1 = 58,
          mask_1 = 121,
          arms = 11,
          pants_1 = 5,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 1,
          tshirt_1 = 12,
          bproof_1 = 2,
          bproof_2 = 3,
          decals_1 = 11,
          torso_1 = 1,
          torso_2 = 3
        },
      }
    },
{
ace = 'SILVER',
name = 'Police Silver Command',
clothes = {
  ['Superintendent Formals'] = {
    -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
    helmet_1 = 9,
    mom = 33,
    dad = 21,
    hair_1 = 1,
  hair_color_1 = 1,
    mask_1 = 0,
    arms = 1,
    pants_1 = 27,
    bags_1 = 0,
    shoes_1 = 11,
    neckarm_1 = 0,
    tshirt_1 = 88,
    bproof_1 = 0,
    decals_1 = 20,
    torso_1 = 35,
    torso_2 = 4
  },
 ['Police Superintendent White shirt'] = {
    -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
    helmet_1 = -1,
    mom = 26,
    dad = 10,
    hair_1 = 5,
  hair_color_1 = 4,
    mask_1 = 0,
    arms = 1,
    pants_1 = 27,
    bags_1 = 0,
    shoes_1 = 10,
    neckarm_1 = 0,
    tshirt_1 = 15,
    bproof_1 = 0,
    decals_1 = 0,
    torso_1 = 31,
    torso_2 = 4,
  },
  ['Chief Superintendent Formals'] = {
    -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
    helmet_1 = 9,
    mom = 14,
    dad = 34,
    hair_1 = 1,
  hair_color_1 = 6,
    mask_1 = 0,
    arms = 1,
    pants_1 = 27,
    bags_1 = 0,
    shoes_1 = 11,
    neckarm_1 = 0,
    tshirt_1 = 88,
    bproof_1 = 0,
    decals_1 = 20,
    torso_1 = 35,
    torso_2 = 5
  },
 ['Chief Superintendent White shirt'] = {
    -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
    helmet_1 = -1,
    mom = 26,
    dad = 10,
    hair_1 = 5,
  hair_color_1 = 4,
    mask_1 = 0,
    arms = 1,
    pants_1 = 27,
    bags_1 = 0,
    shoes_1 = 10,
    neckarm_1 = 0,
    tshirt_1 = 15,
    bproof_1 = 0,
    decals_1 = 0,
    torso_1 = 31,
    torso_2 = 5,
  },
    ['Police Black Vest Superintendent'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 9,
    mom = 35,
    dad = 27,
    hair_1 = 2,
    hair_color_1 = 58,
      mask_1 = 121,
      arms = 11,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 2,
      tshirt_1 = 9,
      bproof_1 = 7,
      decals_1 = 7,
      torso_1 = 1,
      torso_2 = 4
    },
    ['Police HighVis Superintendent'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 9,
    mom = 35,
    dad = 27,
    hair_1 = 2,
    hair_color_1 = 58,
      mask_1 = 121,
      arms = 11,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 1,
      tshirt_1 = 9,
      bproof_1 = 2,
      bproof_2 = 4,
      decals_1 = 1,
      torso_1 = 1,
      torso_2 = 4
    },
    ['Police Black Vest Chief Superintendent'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 9,
      mask_1 = 121,
    mom = 11,
    dad = 21,
    hair_1 = 2,
    hair_color_1 = 58,
      arms = 11,
      pants_1 = 47,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 2,
      tshirt_1 = 9,
      bproof_1 = 6,
      decals_1 = 6,
      torso_1 = 1,
      torso_2 = 5
    },
    ['Police HighVis Chief Superintendent'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 9,
    mom = 9,
    dad = 22,
    hair_1 = 2,
    hair_color_1 = 58,
      mask_1 = 121,
      arms = 11,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 1,
      tshirt_1 = 9,
      bproof_1 = 2,
      bproof_2 = 4,
      decals_1 = 1,
      torso_1 = 1,
      torso_2 = 5
    },
  }
},
{
ace = 'GOLD',
name = 'Police Gold Command',
clothes = {
    ['ACC Black top'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 4,
      mom = 18,
      dad = 27,
      beard_1 = 5,
      beard_2 = 100,
      beard_3 = 1,
      beard_4 = 0,
      hair_1 = 5,
    hair_color_1 = 10,
      mask_1 = 11,
      arms = 4,
      arms_2 = 0,
      pants_1 = 5,
      bags_1 = 0,
      shoes_1 = 25,
      shoes_2 = 0,
      neckarm_1 = 0,
      tshirt_1 = 11,
      bproof_1 = 12,
      decals_1 = 0,
      torso_1 = 5,
      torso_2 = 1
    },
    ['Incident Commander'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 18,
      dad = 27,
      beard_1 = 8,
      beard_2 = 100,
      beard_3 = 11,
      beard_4 = 0,
      hair_1 = 4,
    hair_color_1 = 3,
      mask_1 = 11,
      arms = 4,
      arms_2 = 0,
      pants_1 = 5,
      bags_1 = 3,
      shoes_1 = 25,
      shoes_2 = 0,
      neckarm_1 = 9,
      tshirt_1 = 8,
      bproof_1 = 33,
      decals_1 = 0,
      torso_1 = 31,
      torso_2 = 0
    },
    ['ACC White top'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = -1,
      mom = 18,
      dad = 27,
      beard_1 = 5,
      beard_2 = 100,
      beard_3 = 1,
      beard_4 = 0,
      hair_1 = 5,
    hair_color_1 = 10,
      mask_1 = 11,
      arms = 2,
      arms_2 = 0,
      pants_1 = 5,
      bags_1 = 0,
      shoes_1 = 25,
      shoes_2 = 0,
      neckarm_1 = 14,
      tshirt_1 = 15,
      bproof_1 = 32,
      decals_1 = 23,
      torso_1 = 12,
      torso_2 = 2
    },
   ['Police Deputy Chief Contsable'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 4,
    mom = 2,
    dad = 12,
    hair_1 = 1,
    hair_color_1 = 1,
      mask_1 = 121,
      arms = 11,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 1,
      tshirt_1 = 9,
      bproof_1 = 22,
      decals_1 = 1,
      torso_1 = 1,
      torso_2 = 5
    },
    ['Deputy Chief Constable Formals'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 4,
      mom = 40,
      dad = 1,
      hair_1 = 1,
    hair_color_1 = 8,
      mask_1 = 0,
      arms = 1,
      pants_1 = 27,
      bags_1 = 0,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 88,
      bproof_1 = 0,
      decals_1 = 21,
      torso_1 = 36,
      torso_2 = 4
    },
    ['Deputy Chief Constable White Shirt'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = -1,
      mom = 40,
      dad = 1,
      hair_1 = 1,
    hair_color_1 = 8,
      mask_1 = 0,
      arms = 1,
      pants_1 = 27,
      bags_1 = 0,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 88,
      bproof_1 = 0,
      decals_1 = 0,
      torso_1 = 31,
      torso_2 = 6
    },
    ['ACC formals'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 4,
      mom = 32,
      dad = 31,
      hair_1 = 4,
    hair_color_1 = 2,
      mask_1 = 0,
      arms = 1,
      pants_1 = 27,
      bags_1 = 0,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 88,
      bproof_1 = 0,
      decals_1 = 21,
      torso_1 = 134,
      torso_2 = 0
    },
  }
},
{
  ace = 'MPSERPT',
  name = 'Police Constable',
  clothes = {
    ['PC Black Vest'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 38,
      dad = 32,
      hair_1 = 29,
    hair_color_1 = 2,
      mask_1 = 0,
      arms = 0,
      pants_1 = 5,
      bags_1 = 20,
      shoes_1 = 25,
      neckarm_1 = 0,
      tshirt_1 = 9,
      bproof_1 = 6,
      decals_1 = 6,
      torso_1 = 1
    },
    ['PC High Vis Vest'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 29,
      dad = 10,
      hair_1 = 28,
    hair_color_1 = 2,
      mask_1 = 0,
      arms = 0,
      pants_1 = 5,
      bags_1 = 20,
      shoes_1 = 25,
      neckarm_1 = 0,
      tshirt_1 = 9,
      bproof_1 = 16,
      decals_1 = 6,
      torso_1 = 1
    },
    ['PC Black Long Sleeved Top'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 12,
      dad = 22,
      hair_1 = 11,
    hair_color_1 = 2,
      mask_1 = 11,
      arms = 4,
      pants_1 = 5,
      bags_1 = 30,
      shoes_1 = 25,
      neckarm_1 = 13,
      tshirt_1 = 9,
      bproof_1 = 6,
      decals_1 = 11,
      torso_1 = 5
    },
    ['PC High Vis Long Sleeved'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mask_1 = 0,
      mom = 12,
      dad = 22,
      hair_1 = 11,
    hair_color_1 = 2,
      arms = 4,
      pants_1 = 5,
      bags_1 = 20,
      shoes_1 = 25,
      neckarm_1 = 0,
      tshirt_1 = 11,
      bproof_1 = 16,
      decals_1 = 6,
      torso_1 = 5
    },
    ['PC Long Sleeved'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 12,
      dad = 22,
      hair_1 = 1,
    hair_color_1 = 2,
      mask_1 = 0,
      arms = 4,
      pants_1 = 5,
      bags_1 = 21,
      shoes_1 = 25,
      neckarm_1 = 69,
      tshirt_1 = 10,
      bproof_1 = 8,
      decals_1 = 7,
      torso_1 = 5
    },
    ['Police Constable Formals'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 19,
      dad = 13,
      hair_1 = 2,
    hair_color_1 = 12,
      mask_1 = 0,
      arms = 1,
      pants_1 = 27,
      bags_1 = 0,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 88,
      bproof_1 = 0,
      decals_1 = 0,
      torso_1 = 35
    },
    ['Senior Constable Formals'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 14,
      dad = 19,
      hair_1 = 2,
    hair_color_1 = 8,
      mask_1 = 0,
      arms = 1,
      pants_1 = 27,
      bags_1 = 0,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 88,
      bproof_1 = 0,
      decals_1 = 0,
      torso_1 = 36,
      torso_2 = 1,
    }
  }
},
{
  ace = 'BTPR&P',
  name = 'British Transport Police',
  clothes = {
    ['BTP High Vis Long Sleeved'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 14,
      dad = 19,
      hair_1 = 1,
    hair_color_1 = 2,
      mask_1 = 11,
      arms = 4,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 12,
      tshirt_1 = 9,
      bproof_1 = 10,
      decals_1 = 9,
      torso_1 = 5
      
    },
    ['BTP Black Long Sleeved'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 1,
      dad = 17,
      hair_1 = 2,
    hair_color_1 = 8,
      mask_1 = 121,
      arms = 4,
      pants_1 = 5,
      bags_1 = 9,
      shoes_1 = 25,
      neckarm_1 = 12,
      tshirt_1 = 9,
      bproof_1 = 11,
      decals_1 = 8,
      torso_1 = 5
     
    },
    ['BTP Black Short Sleeved'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 10,
      dad = 29,
      hair_1 = 2,
    hair_color_1 = 3,
      mask_1 = 11,
      arms = 0,
      pants_1 = 5,
      bags_1 = 88,
      shoes_1 = 25,
      neckarm_1 = 12,
      tshirt_1 = 9,
      bproof_1 = 11,
      decals_1 = 9,
      torso_1 = 1
      
    },
    ['BTP Armed Black vest'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 45,
      dad = 24,
      hair_1 = 7,
    hair_color_1 = 60,
      mask_1 = 11,
      arms = 0,
      pants_1 = 5,
      bags_1 = 0,
      shoes_1 = 25,
      neckarm_1 = 2,
      tshirt_1 = 8,
      bproof_1 = 11,
      decals_1 = 6,
      torso_1 = 4
    }
  }
},
{
  ace = 'ALL',
  name = 'Trainers',
  clothes = {
    ['Trianer 1'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 7,
      mom = 29,
      dad = 20,
      hair_1 = 2,
    hair_color_1 = 45,
      glasses_1 = 2,
      glasses_2 = 3,
      mask_1 = 11,
      arms = 0,
      pants_1 = 5,
      bags_1 = 87,
      shoes_1 = 25,
      neckarm_1 = 6,
      tshirt_1 = 11,
      bproof_1 = 24,
      decals_1 = 3,
      torso_1 = 1
      
    },
    ['Trainer 2'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 20,
      dad = 30,
      hair_1 = 7,
    hair_color_1 = 2,
      glasses_1 = 37,
      mask_1 = 11,
      arms = 0,
      pants_1 = 5,
      bags_1 = 0,
      shoes_1 = 54,
      neckarm_1 = 5,
      tshirt_1 = 8,
      bproof_1 = 15,
      decals_1 = 1,
      torso_1 = 1
     
    },
    ['Trainer 3'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = 1,
      mom = 21,
      dad = 18,
      hair_1 = 2,
    hair_color_1 = 8,
      glasses_1 = 37,
      mask_1 = 11,
      arms = 11,
      pants_1 = 13,
      bags_1 = 87,
      shoes_1 = 54,
      neckarm_1 = 1,
      tshirt_1 = 11,
      bproof_1 = 24,
      decals_1 = 1,
      torso_1 = 95,
    }
  }
},
{
      ace = 'ALL',
      name = 'British Army',
      clothes = {
        ['Army With Vest'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 37,
          mom = 14,
          dad = 19,
          hair_1 = 1,
        hair_color_1 = 8,
          glasses_1 = 15,
          glasses_2 = 7,
          mask_1 = 11,
          arms = 4,
          pants_1 = 40,
          bags_1 = 0,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 55,
          tshirt_1 = 88,
          bproof_1 = 31,
          decals_1 = 0,
          torso_1 = 32
        },
        ['Army No Vest'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 37,
          mom = 21,
          dad = 29,
          hair_1 = 5,
        hair_color_1 = 8,
          hair_1 = 5,
          hair_color_1 = 4,
          mask_1 = 11,
          arms = 4,
          pants_1 = 40,
          pants_2 = 3,
          bags_1 = 0,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 3,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 32,
          torso_2 = 4
        },
        ['Army tactial'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 35,
          mom = 4,
          dad = 13,
          hair_1 = 4,
        hair_color_1 = 18,
          hair_1 = 19,
          hair_color_1 = 4,
          mask_1 = 11,
          arms = 4,
          pants_1 = 40,
          pants_2 = 3,
          bags_1 = 0,
          shoes_1 = 12,
          neckarm_1 = 3,
          tshirt_1 = 15,
          bproof_1 = 31,
          decals_1 = 11,
          torso_1 = 32,
          torso_2 = 4
        },
        ['Army Black Vest'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 37,
          mom = 23,
          dad = 11,
          hair_1 = 5,
        hair_color_1 = 13,
          mask_1 = 11,
          arms = 4,
          pants_1 = 40,
          pants_2 = 2,
          bags_1 = 0,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 18,
          decals_1 = 0,
          torso_1 = 32,
          torso_2 = 3
        },
        ['Army Funny Hat'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 34,
          mom = 34,
          dad = 32,
          hair_1 = 5,
        hair_color_1 = 5,
          mask_1 = 116,
          mask_2 = 20,
          arms = 141,
          arms_2 = 3,
          pants_1 = 40,
          bags_1 = 43,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 112,
          tshirt_1 = 130,
          bproof_1 = 31,
          decals_1 = 0,
          torso_1 = 32,
          torso_2 = 5
        },
        ['Army Medic'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 37,
          mask_1 = 11,
          arms = 141,
          arms_2 = 8,
          pants_1 = 40,
          bags_1 = 67,
          shoes_1 = 12,
          shoes_2 = 6,
          neckarm_1 = 112,
          tshirt_1 = 16,
          bproof_1 = 34,
          decals_1 = 0,
          torso_1 = 32
        },
        ['Army Flight Suit'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 23,
          mom = 34,
          dad = 32,
          hair_1 = 5,
        hair_color_1 = 5,
          mask_1 = -1,
          arms = 4,
          pants_1 = 111,
          bags_1 = 0,
          shoes_1 = 2,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 287
        },
      }
    },

    {
      ace = 'ALL',
      name = 'Military Police',
      clothes = {
        ['MP 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 39,
          mom = 23,
          dad = 18,
          hair_1 = 1,
        hair_color_1 = 9,
          mask_1 = 11,
          arms = 0,
          pants_1 = 0,
          bags_1 = 0,
          shoes_1 = 2,
          neckarm_1 = 0,
          tshirt_1 = 73,
          bproof_1 = 31,
          decals_1 = 0,
          torso_1 = 39
        },
        ['MP 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 39,
          mom = 31,
          dad = 28,
          hair_1 = 1,
        hair_color_1 = 1,
        mask_1 = 11,
        arms = 0,
        pants_1 = 0,
        bags_1 = 0,
        shoes_1 = 2,
        neckarm_1 = 123,
        tshirt_1 = 8,
        bproof_1 = 6,
        decals_1 = 6,
        torso_1 = 39
      },
        ['MP 3'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 39,
          mom = 121,
          dad = 22,
          hair_1 = 1,
        hair_color_1 = 2,
          mask_1 = 11,
          arms = 4,
          pants_1 = 40,
          pants_2 = 2,
          bags_1 = 0,
          shoes_1 = 54,
          shoes_2 = 0,
          neckarm_1 = 119,
          tshirt_1 = 7,
          bproof_1 = 9,
          decals_1 = 0,
          torso_1 = 32,
          torso_2 = 3,
        },
        ['MP 4'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 39,
          mom = 3,
          dad = 2,
          hair_1 = 1,
        hair_color_1 = 5,
        mask_1 = 11,
        arms = 0,
        pants_1 = 0,
        bags_1 = 0,
        shoes_1 = 2,
        neckarm_1 = 123,
        tshirt_1 = 7,
        bproof_1 = 9,
        decals_1 = 0,
        torso_1 = 40
        }
      }
    },
          
    {
      ace = 'PLFB',
      name = 'Probationary Firefighter',
      clothes = {
        ['Probationary Firefighter'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          mask_1 = 0,
          mom = 10,
          dad = 37,
          hair_1 = 38,
        hair_color_1 = 2,
          arms = 8,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 13
        }
      }
    },
  
    {
      ace = 'BRONZE',
      name = 'LFB Bronze command',
      clothes = {
        ['Sub Officer'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 3,
          mom = 5,
          dad = 40,
          hair_1 = 28,
        hair_color_1 = 25,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 13,
          torso_2 = 2,
        },
        ['Leading FireFighter'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 2,
          mom = 5,
          dad = 40,
          hair_1 = 28,
        hair_color_1 = 25,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 13,
          torso_2 = 1,

        },
        ['Sub White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 2
        },
        ['Lead Fire White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 1
        }
      }
    },
    {
      ace = 'SILVER',
      name = 'LFB Silver Command',
      clothes = {
        ['Group Commander'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mom = 5,
          dad = 40,
          hair_1 = 28,
        hair_color_1 = 25,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 13,
          torso_2 = 4,
        },
        ['Incident Commander'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 3,
          mom = 44,
          dad = 10,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 8,
          torso_2 = 1
        },
        ['Station Commander'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mom = 33,
          dad = 44,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 13,
          torso_2 = 3
        },
        ['Area Manager'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mom = 33,
          dad = 44,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 13,
          torso_2 = 5
        },
        ['Group White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 4
        },
        ['Station White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 3
        },
        ['AM White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 5
        }
      }
    },
    {
      ace = 'GOLD',
      name = 'LFB Gold Command',
      clothes = {
        ['Commssioner'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mom = 5,
          dad = 40,
          hair_1 = 28,
        hair_color_1 = 25,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 13,
          torso_2 = 7,
        },
        ['Incident Commander'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 3,
          mom = 44,
          dad = 10,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 8,
          torso_2 = 1
        },
        ['Deputy Commissioner'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mom = 33,
          dad = 44,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 3,
          bags_1 = 9,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 2,
          torso_1 = 13,
          torso_2 = 6,
        },
        ['Com White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 7
        },
        ['DCOM White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
          torso_2 = 6
        }
      }
    },

    {
      ace = 'LFB',
      name = 'London Fire Brigade',
      clothes = {
        ['LFB Station Rest Gear'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          hair_1 = 36,
        hair_color_1 = 7,
          mask_1 = 0,
          arms = 11,
          pants_1 = 2,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 9,
        },
        ['LFB Formal Wear'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 34,
          dad = 29,
          hair_1 = 35,
        hair_color_1 = 9,
          mask_1 = 0,
          arms = 11,
          pants_1 = 2,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 10,
        },
        ['LFB Mask on Breathing Aparatus'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 1,
          mom = 38,
          dad = 28,
          hair_1 = 34,
        hair_color_1 = 7,
          mask_1 = 0,
          arms = 15,
          pants_1 = 3,
          bags_1 = 0,
          shoes_1 = 12,
          neckarm_1 = 3,
          tshirt_1 = 3,
          bproof_1 = 0,
          decals_1 = 61,
          torso_1 = 13,
        },
        ['LFB Mask Off Breathing Aparatus'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 1,
          mom = 44,
          dad = 49,
          hair_1 = 33,
        hair_color_1 = 3,
          mask_1 = 0,
          arms = 15,
          pants_1 = 3,
          bags_1 = 0,
          shoes_1 = 12,
          neckarm_1 = 3,
          tshirt_1 = 2,
          bproof_1 = 0,
          decals_1 = 61,
          torso_1 = 13,
        },
        ['LFB Turnout Gear'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 2,
          helmet_2 = 1,
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 11,
          pants_1 = 3,
          bags_1 = 48,
          shoes_1 = 25,
          neckarm_1 = 108,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 61,
          torso_1 = 13,
        },
        ['LFB White shirts'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          mom = 26,
          dad = 23,
          hair_1 = 32,
        hair_color_1 = 4,
          mask_1 = 0,
          arms = 0,
          pants_1 = 2,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 12,
        }
      }
    },
    {
      ace = 'TRAFFICOFFICER',
      name = 'Highways England',
      clothes = {
         ['Highways 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          hair_1 = 38,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 1,
          pants_1 = 10,
          bags_1 = 88,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 14,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 23,
        },
        ['Highways 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          hair_1 = 74,
        hair_color_1 = 58,
          mask_1 = 0,
          arms = 1,
          pants_1 = 2,
          bags_1 = 88,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 23,
        }
      }  
    },
    {
      ace = 'MAG',
      name = 'CPS',
      clothes = {
         ['Lawyer 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 123,
          mom = 12,
          dad = 22,
          hair_1 = 2,
        hair_color_1 = 3,
          mask_1 = 0,
          arms = 1,
          pants_1 = 22,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 148,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 294,
        },
        ['Lawyer 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 123,
          mom = 12,
          dad = 22,
          hair_1 = 21,
        hair_color_1 = 58,
          mask_1 = 0,
          arms = 1,
          pants_1 = 22,
          pants_2 = 5,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 148,
          tshirt_2 = 1,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 294,
          torso_2 = 5,
        },
        ['Jugde 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 123,
          mom = 33,
          dad = 55,
          hair_1 = 7,
        hair_color_1 = 5,
          mask_1 = 0,
          arms = 4,
          pants_1 = 24,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 22,
          tshirt_1 = 146,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 294,
        },
        ['jugde 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 123,
          mom = 28,
          dad = 21,
          hair_1 = 5,
        hair_color_1 = 5,
          mask_1 = 0,
          arms = 4,
          pants_1 = 24,
          bags_1 = 0,
          shoes_1 = 11,
          neckarm_1 = 26,
        neckarm_2 = 2,
          tshirt_1 = 146,
        tshirt_2 = 10,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 294,
          torso_2 = 1,
        },
      }  
    },
    {
      ace = 'TRAFFICOFFICER',
      name = 'AA',
      clothes = {
        ['AA 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 40,
          mom = 12,
          dad = 22,
          hair_1 = 11,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 10,
          bags_1 = 88,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 109,
          bproof_1 = 28,
          decals_1 = 0,
          torso_1 = 27,
        },
        ['AA 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 40,
          mom = 12,
          dad = 22,
          hair_1 = 11,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 6,
          pants_1 = 9,
          bags_1 = 88,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 88,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 28,
        },
        ['AA 3'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mom = 12,
          dad = 22,
          hair_1 = 11,
        hair_color_1 = 2,
          mask_1 = 0,
          arms = 0,
          pants_1 = 10,
          bags_1 = 88,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 21,
        }
      }
    },
    {
      ace = 'MOD',
      name = 'Modertaor',
      clothes = {
        ['Mod 1'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          mom = 34,
          dad = 11,
          hair_1 = 3,
          beard_1 = 11,
          beard_2 = 100,
          beard_3 = 6,
          beard_4 = 0,
        hair_color_1 = 17,
          arms = 1,
          pants_1 = 60,
          bags_1 = 0,
          shoes_1 = 1,
          shoes_2 = 1,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 136
        },
        ['Mod 2'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          mom = 34,
          dad = 11,
          hair_1 = 3,
          beard_1 = 18,
          beard_2 = 100,
          beard_3 = 6,
          beard_4 = 0,
        hair_color_1 = 17,
          arms = 1,
          pants_1 = 60,
          bags_1 = 0,
          shoes_1 = 1,
          shoes_2 = 2,
          neckarm_1 = 0,
          tshirt_1 = 15,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 135,
          torso_2 = 1
        }
      }
    },
    
    {
      ace = 'STUPARA',
      name = 'Student Paramedic',
      clothes = {
        ['Student Paramedic Top'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 3,
          arms = 171,
          pants_1 = 13,
          bags_1 = 0,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 14,
          torso_2 = 1,
       },
       ['Student Paramedic Jacket'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 6,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 21,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 11,
        torso_2 = 1,
     },
     ['Student Formals'] = {
      -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
      helmet_1 = -1,
      mask_1 = 0,
      arms = 0,
      pants_1 = 96,
      pants_2 = 1,
      bags_1 = 7,
      shoes_1 = 11,
      neckarm_1 = 0,
      tshirt_1 = 17,
      bproof_1 = 0,
      decals_1 = 0,
      torso_1 = 7,
      torso_2 = 1,
    },
  }
},
    {
      ace = 'PARA',
      name = 'London Ambulance Service',
      clothes = {
        ['NHS Polo Shirt'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 3,
          arms = 171,
          pants_1 = 13,
          bags_1 = 0,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 14,
        },
        ['NHS Vests'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = 3,
          mask_1 = 0,
          arms = 0,
          pants_1 = 6,
          bags_1 = 0,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 3,
          decals_1 = 0,
          torso_1 = 14,
        },
        ['NHS Jacket'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 0,
          pants_1 = 6,
          bags_1 = 0,
          shoes_1 = 25,
          neckarm_1 = 0,
          tshirt_1 = 21,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 11,
        },
        ['NHS Formals'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 0,
          pants_1 = 96,
          pants_2 = 1,
          bags_1 = 7,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 7,
        },
  
      }
    },
  
    {
      ace = 'BRONZE',
      name = 'LAS Bronze Command',
      clothes = {
        ['Senior Paramedic'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 0,
          pants_1 = 96,
          pants_2 = 1,
          bags_1 = 7,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 7,
          torso_2 = 3
        },
        ['Advanced Paramedic'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 0,
          pants_1 = 96,
          pants_2 = 1,
          bags_1 = 7,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 7,
          torso_2 = 4
        },
        ['Senior Paramedic Long Sleeved'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 1,
          pants_1 = 96,
          pants_2 = 1,
          bags_1 = 7,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 6,
          torso_2 = 3
        },
        ['Advanced Paramedic Long Sleeved'] = {
          -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
          helmet_1 = -1,
          mask_1 = 0,
          arms = 1,
          pants_1 = 96,
          pants_2 = 1,
          bags_1 = 7,
          shoes_1 = 11,
          neckarm_1 = 0,
          tshirt_1 = 17,
          bproof_1 = 0,
          decals_1 = 0,
          torso_1 = 6,
          torso_2 = 4
        },
        ['AP Polo'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 3,
        arms = 171,
        pants_1 = 13,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 14,
        torso_2 = 9,
      },
        ['S/Paramedic Polo'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 3,
        arms = 171,
        pants_1 = 13,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 14,
        torso_2 = 7,
      },
      ['S/ Paramedic Jacket'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 6,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 21,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 11,
        torso_2 = 7,
      },
      ['AP Jacket'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 6,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 21,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 11,
        torso_2 = 8,
      },
  
    }
  },
  {
    ace = 'SILVER',
    name = 'LAS Sliver Command',
    clothes = {
      ['Opertaions Manager'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 96,
        pants_2 = 1,
        bags_1 = 7,
        shoes_1 = 11,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 37,
      },
      ['Locality manager'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 96,
        pants_2 = 1,
        bags_1 = 7,
        shoes_1 = 11,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 41,
      },
      ['Operations Manager Long Sleeved'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 1,
        pants_1 = 96,
        pants_2 = 1,
        bags_1 = 7,
        shoes_1 = 11,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 19,
      },
      ['Locality manager Long Sleeved'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 1,
        pants_1 = 96,
        pants_2 = 1,
        bags_1 = 7,
        shoes_1 = 11,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 22,
      },
      ['LM Polo'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 3,
        arms = 171,
        pants_1 = 13,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 14,
        torso_2 = 12,
      },
      ['Ops Polo'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 3,
        arms = 171,
        pants_1 = 13,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 17,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 14,
        torso_2 = 10,
      },
      ['LM Jacket'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 6,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 21,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 11,
        torso_2 = 10,
      },
      ['OPS Jacket'] = {
        -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
        helmet_1 = -1,
        mask_1 = 0,
        arms = 0,
        pants_1 = 6,
        bags_1 = 0,
        shoes_1 = 25,
        neckarm_1 = 0,
        tshirt_1 = 21,
        bproof_1 = 0,
        decals_1 = 0,
        torso_1 = 11,
        torso_2 = 9,
      },
    }
  },
      {
        ace = 'GOLD',
        name = 'LAS Gold Command',
        clothes = {
          ['Assisant Chief Ambulance Officer'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 17,
          },
          ['Deputy Chief Ambulance Officer'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 16,
          },
          ['DCAO Long Sleeved'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 1,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 33,
          },
          ['ACAO Long Sleeved'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 1,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 38,
          },
          ['Chief Ambulance Officer'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 18,
          },
          ['CAO Long Sleeved'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 1,
            pants_1 = 96,
            pants_2 = 1,
            bags_1 = 7,
            shoes_1 = 11,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 20,
          },
          ['CAO Polo'] = {
              -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
              helmet_1 = -1,
              mask_1 = 3,
              arms = 171,
              pants_1 = 13,
              bags_1 = 0,
              shoes_1 = 25,
              neckarm_1 = 0,
              tshirt_1 = 17,
              bproof_1 = 0,
              decals_1 = 0,
              torso_1 = 14,
              torso_2 = 15,
            },
          ['DCAO Polo'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 3,
            arms = 171,
            pants_1 = 13,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 14,
            torso_2 = 13,
          },
          ['ACAO Polo'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 3,
            arms = 171,
            pants_1 = 13,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 0,
            tshirt_1 = 17,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 14,
            torso_2 = 14,
          },
          ['ACAO Jacket'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 6,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 0,
            tshirt_1 = 21,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 11,
            torso_2 = 13,
          },
          ['DCAO Jacket'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 6,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 0,
            tshirt_1 = 21,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 11,
            torso_2 = 12,
          },
          ['CAO Jacket'] = {
            -- HERE YOU PUT YOUR OUTFIT INFORMATION AS I SAID ION THE DISCORD
            helmet_1 = -1,
            mask_1 = 0,
            arms = 0,
            pants_1 = 6,
            bags_1 = 0,
            shoes_1 = 25,
            neckarm_1 = 0,
            tshirt_1 = 21,
            bproof_1 = 0,
            decals_1 = 0,
            torso_1 = 11,
            torso_2 = 14,
          },
    }
}
}
  --[[

        ------- IMPORTANT PLEASE READ ------

        OUTFIT INFORMATION CAN CONTAIN ANY OF THE FOLLOWING.

        sex = 1,
        mom = 21,
        dad = 0,
        face_md_weight = 50,
        skin_md_weight = 50,
        nose_1 = 0,
        nose_2 = 0,
        nose_3 = 0,
        nose_4 = 0,
        nose_5 = 0,
        nose_6 = 0,
        cheeks_1 = 0,
        cheeks_2 = 0,
        cheeks_3 = 0,
        lip_thickness = 0,
        jaw_1 = 0,
        jaw_2 = 0,
        chin_1 = 0,
        chin_2 = 0,
        chin_3 = 0,
        chin_4 = 0,
        neck_thickness = 0,
        hair_1 = 0,
        hair_2 = 0,
        hair_color_1 = 0,
        hair_color_2 = 0,
        tshirt_1 = 0,
        tshirt_2 = 0,
        torso_1 = 0,
        torso_2 = 0,
        decals_1 = 0,
        decals_2 = 0,
        arms = 15,
        arms_2 = 0,
        pants_1 = 0,
        pants_2 = 0,
        shoes_1 = 0,
        shoes_2 = 0,
        mask_1 = 0,
        mask_2 = 0,
        bproof_1 = 0,
        bproof_2 = 0,
        neckarm_1 = 0,
        neckarm_2 = 0,
        helmet_1 = -1,
        helmet_2 = 0,
        glasses_1 = -1,
        glasses_2 = 0,
        lefthand_1 = -1,
        lefthand_2 = 0,
        righthand_1 = -1,
        righthand_2 = 0,
        bags_1 = 0,
        bags_2 = 0,
        eye_color = 0,
        eye_squint = 0,
        eyebrows_2 = 100,
        eyebrows_1 = 0,
        eyebrows_3 = 0,
        eyebrows_4 = 0,
        eyebrows_5 = 0,
        eyebrows_6 = 0,
        makeup_type = 0,
        makeup_1 = 255,
        makeup_2 = 100,
        makeup_3 = 255,
        makeup_4 = 255,
        lipstick_1 = 255,
        lipstick_2 = 100,
        lipstick_3 = 0,
        lipstick_4 = 0,
        ears_1 = -1,
        ears_2 = 0,
        chest_1 = 255,
        chest_2 = 100,
        chest_3 = 0,
        chest_4 = 0,
        bodyb_1 = 255,
        bodyb_2 = 100,
        bodyb_3 = 255,
        bodyb_4 = 100,
        age_1 = 255,
        age_2 = 100,
        blemishes_1 = 255,
        blemishes_2 = 100,
        blush_1 = 255,
        blush_2 = 100,
        blush_3 = 0,
        complexion_1 = 255,
        complexion_2 = 100,
        sun_1 = 255,
        sun_2 = 100,
        moles_1 = 255,
        moles_2 = 100,
        beard_1 = 255,
        beard_2 = 100,
        beard_3 = 0,
        beard_4 = 0



]]




ShowNotification = function(msg)
	SetNotificationTextEntry('STRING')
	AddTextComponentString(msg)
	DrawNotification(0,1)
end

DrawText3Ds = function(coords, text)
    local x,y,z = table.unpack(coords)
    local onScreen,_x,_y=World3dToScreen2d(x,y,z+1)
    SetTextScale(0.50, 0.50)
    SetTextFont(4)
    SetTextProportional(1)
    SetTextColour(255, 255, 255, 215)
    SetTextEntry("STRING")
    SetTextCentre(1)
    AddTextComponentString(text)
    DrawText(_x,_y)
    local factor = (string.len(text)) / 370
    DrawRect(_x,_y+0.0145, 0.035+ factor, 0.03, 41, 11, 41, 68)
end